---
- hosts: db
  become: true

  tasks:
  - name: Create XFS filesystem on /dev/sdb
    ansible.builtin.filesystem:
      fstype: xfs
      dev: /dev/sdb

  - name: Mount volume
    ansible.builtin.mount:
      path: /var/lib/mysql
      src: /dev/sdb
      fstype: xfs
      state: mounted

  - name: Install MariaDB, also starts the service
    ansible.builtin.apt:
      name: mariadb-server
      update_cache: yes

  - name: Set MariaDB bind-address
    ansible.builtin.ini_file:
      path: /etc/mysql/mariadb.conf.d/90-server.cnf
      section: mysqld
      option: bind-address
      value: "{{ ansible_default_ipv4.address }}"
      backup: yes
    notify:
    - restart MariaDB

  - name: Make sure MariaDB is running and enabled
    ansible.builtin.systemd:
      name: mariadb
      state: started
      enabled: yes

  - name: Install PyMySQL, needed by Ansible MySQL module
    ansible.builtin.apt:
      name: python3-pymysql


  handlers:
  - name: restart MariaDB
    ansible.builtin.systemd:
      name: "mariadb"
      state: restarted
